baseURL: "https://econf19.classes.andrewheiss.com/"
languageCode: en-us
title: Economy, Society, and Public Policy
theme: "ath-tufte-hugo_archivo"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: True
disableKinds: ["taxonomy", "taxonomyTerm"]
# Disable taxonomies
# JUST KIDDING this breaks all content/subdirectories for whatever reason
# taxonomies:
#   tag: ""
#   group: ""
#   category: ""
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Reference
      url: /reference/
      weight: 4
    - name: Slack
      url: "https://pmap8141fall2019.slack.com"
      weight: 5
params:
  author: Andrew Heiss
  thumbnail: /images/econ_meta.png
  instructor: 
    name: Dr. Andrew Heiss
    email: aheiss@gsu.edu
    url: "https://www.andrewheiss.com"
    twitter: andrewheiss
    github: andrewheiss
    office: "357 Andrew Young School"
  course:
    number: "PMAP 8141"
    semester: "Fall 2019"
    days: "Thursdays"
    time: "7:15–9:45 PM"
    location: "Classroom South 301"
    twitter: andrewheiss
    dates: "August 29–December 4, 2019"
    github: "andrewheiss/econf19.classes.andrewheiss.com"
    slack: "https://pmap8141fall2019.slack.com/"
    copyrightYear: "2019"
    contactDetails: >-
      Office hours: [Sign up here.](https://calendly.com/andrewheiss/meeting/)<br><br><small>E-mail is the best way to get in contact with me. I will try to respond to all course-related e-mails within 24 hours (*really*), but also remember that life can be busy and chaotic for everyone (including me!), so if I don't respond to your e-mail right away, don't worry!</small>
  university: 
    name: Georgia State University
    url: "https://www.gsu.edu"
  school:
    name: Andrew Young School of Policy Studies
    url: "https://aysps.gsu.edu/"
  description: "Understand and use economic reasoning to evaluate public policy"
  primaryColor: "#BF616A"
  secondaryColor: "#5E81AC"
  credits: >-
    Hex icon by Andrew Heiss.<br>[Nord color scheme](https://github.com/arcticicestudio/nord) from [Arctic Ice Studio](http://arcticicestudio.com/).
  logo:
    url: /images/econ_hires.png
    alt: Economy, Society, and Public Policy
  meta:
    twitterSite: "@andrewheiss"
    twitterCreator: "@andrewheiss"
    fbAuthor: "https://www.facebook.com/andrewheiss"
