---
title: "Assignments"
slug: assignments
---

# Preparation

<span class="newthought">You will get the most out of this class</span> if you (1) attend class, (2) complete all the readings, and (3) engage^[Take detailed notes, watch the videos and supplementary content, work through the examples given in the textbook, have vivid dreams about them, etc.]  with the readings.^[Also (4) ask for help from me or the TA!]

You will be graded on your attendance and preparation through regular self-reporting backed by the honor system.^[Be honest!] At the beginning of every class, I will post a quiz on iCollege with the following questions:

1. Are you here in class today?
    - Yes (*3.5 points*)
    - No (*0 points*)
2. How much of today's reading did you finish?
    - 100% (*6 points*)
    - 75–99% (*5 points*)
    - 50–74% (*4 points*)
    - 11–49% (*2 points*)
    - 0–10% (*0 points*)
3. How well did you read?
    - I was engaged and read carefully (*6 points*)
    - I was fairly engaged and read fairly carefully (*4 points*)
    - I skimmed it (*2 points*)
    - I didn't read it at all (*0 points*)
4. Did you listen to a podcast episode or read an economics-related article outside of the regular readings?
    - Yes (*2 points*)
    - No (*0 points*)

Each day is worth 17.5 points. *It is unlikely that you'll score an 17.5 every day.*^[But it would be amazing if you did!] I will shift the distribution of everyone's final preparation score up at the end of the course.


# Problem sets

<span class="newthought">To practice solving microeconomic problems</span> you will complete a series of 8 problem sets. Many of the questions on these assignments will come from *Economy, Society, and Public Policy*, some will come from previous courses, and others will come from my head.

There are 10 possible problem sets on the schedule. **You must turn in 8 of the 10 problem sets**. You need to show that you made a good faith effort to work each question. I will not grade these in detail. The problem sets will be graded using a check system:

- ✔+: ^[{-} *44 points (110%) in gradebook*] Problem set is 100% completed. Every question was attempted and answered, and most answers are correct. Work is exceptional. I will not assign these often.
- ✔: ^[{-} *37 points (92.5%) in gradebook*] Problem set is 70–99% complete and most answers are correct. **This is the expected level of performance.**
- ✔−: ^[{-} *20 points (50%) in gradebook*] Problem set is less than 70% complete and/or most answers are incorrect. This indicates that you need to improve next time. I will hopefully not asisgn these often.

You may (and should!) work together on the problem sets, but *you must turn in your own answers.* You cannot work in groups of more than **four** people, and you must note who participated in the group in your assignment.


# Talk like an economist

<span class="newthought">One of the objectives of this class</span> is to "explain social phenomena using economic vocabulary and reasoning", or in less jargony language, be able to talk like an economist. 

There are two assignments that will help with this:

## Listen to podcasts or read economics-related articles.

The [course materials section of the syllabus](/syllabus/#course-materials) explains that you need to listen to at least one episode of an economics- or policy-related podcast every week, or read economics- and policy-related journalism. We will discuss current economic and policy events and research at the beginning of every class, and these podcasts will be an excellent source of material for these discussions.

## Present a brief economic briefing

Near the end of the semester, you will prepare a 5-minute brief where you use economic concepts to explain some pattern or behavior you have observed in your own environment. These do not need to be big issues, but they do need to be real. Being creative is a bonus.^[Don't just explain how supply and demand change for a certain product or whatever—look for a Freakonomics-type question to answer, like [why the McRib follows a strange schedule](https://www.theawl.com/2011/11/a-conspiracy-of-hogs-the-mcrib-as-arbitrage/) (don't do that one, though, obviously).]

You will present your brief to me individually in person during the final weeks of the semester. I will post a signup sheet around November 20. You have 5 minutes to present, and then you will have up to 5 minutes of follow up questions from me.


# Exams

<span class="newthought">There will be two exams</span> covering (1) capitalism, markets, power, and institutions and core economic models, and (2) market failures and government intervention in the economy.

You will take these exams online through iCollege. The exams will be timed, but you can use notes and readings and [the Google](https://www.youtube.com/watch?v=AQ45fO1uiOQ). You must take the exams on your own though, and not talk to anyone about them.^[Again, be honest.]


# Final project

<span class="newthought">At the end of the course,</span> you will demonstrate your knowledge of economics, society, and public policy by completing a final project.

Project details will be posted later once I settle on the best form for it. This much is certain so far:

- You will use economic principles to analyze some sort of real-world, public management-related data
- It will be so much fun!

There is no final exam. This project is your final exam.
